### ISSUE TITLE
Nest media queries in block

### ISSUE THREAD

**Issue by jacobp100** [davidtheclark/postcss-simple-extend#11]
Suggestion,

``` css
@define-placeholder gigantic {
  font-size: 40em;

  @media (max-width: 600px) {
    font-size: 20em;
  }
}
```

Or,

``` css
@define-placeholder gigantic {
  font-size: 40em;
}

@extend-placeholder (max-width: 600px) gigantic {
  font-size: 20em;
}
```
