### ISSUE TITLE
@define-extend placeholder does not @extend another placeholder

### ISSUE THREAD

**Issue by Xaviju** [davidtheclark/postcss-simple-extend#2]
This is a feature request. I try to modularize my extends as much as possible so I tried to create my buttons styles separating basic from modular styles. I used to do this is Sass with multiple extend declarations.

``` scss
@define-extend button {
    font-weight: 100;
    color: var(--white);
    padding: .4rem 2.5rem;
    transition: all .3s linear;
    vertical-align: middle;
}

@define-extend button-green {
    @extend button;
    background: var(--green);
}

.button {
    @extend button-green
}
```

Does not wrks, instead

``` scss
@define-extend button {
    font-weight: 100;
    color: var(--white);
    padding: .4rem 2.5rem;
    transition: all .3s linear;
    vertical-align: middle;
}

@define-extend button-green {
    background: var(--green);
}

.button {
    @extend button
    @extend button-green
}
```

Works perfectly but it is a little bit more messy in the long term.
