### ISSUE TITLE
"Extending at-rules cannot occur at the root level"

### ISSUE THREAD

**Issue by teddybradford** [davidtheclark/postcss-simple-extend#5]
The console throws the error `Extending at-rules cannot occur at the root level` while processing the following markup:

``` css
@define-placeholder smallCaps {
  text-transform: lowercase;
  font-variant: small-caps;
  font-family: var(--type-primaryFontFamily);
  font-weight: 700;
  line-height: 1;
  letter-spacing: 0.12em;
}

th {
  @extend smallCaps;
}
```

Shouldn't this work? The `@extend` is inside the `th {}` block, not the root level.
